export const data = [
  {
    id: 0,
    title: "Buy",
    icon: "https://s3.ap-south-1.amazonaws.com/lands-and-homes/icon_image/1683612140buy.svg",
    tags: [
      "Flat/Apartment",
      "Builder Floor",
      "Independent House",
      "Independent Villa",
      "Pent House",
      "Residential land",
      "Farm House",
      "Serviced Apartment",
      "1RK/Studio Apartment",
      "Villament",
      "Others",
    ],
    status: ["budget", "bedroom", "construction status", "posted by", "area"],
  },
  {
    id: 1,
    title: "Rent",
    icon: "https://s3.ap-south-1.amazonaws.com/lands-and-homes/icon_image/1683612180rent.svg",
    tags: ["abc", "cdf"],
    status: ["budget", "bedroom", "construction status", "posted by", "area"],
  },
  {
    id: 2,
    title: "PG/Co-living",
    icon: "https://s3.ap-south-1.amazonaws.com/lands-and-homes/icon_image/1683612212pg-coliving.svg",
    tags: ["abc", "cdf"],
    status: ["budget", "bedroom", "construction status", "posted by", "area"],
  },
  {
    id: 3,
    title: "Coworking",
    icon: "https://s3.ap-south-1.amazonaws.com/lands-and-homes/icon_image/1683612195coworking.svg",
    tags: ["abc", "cdf"],
    status: ["budget", "bedroom", "construction status", "posted by", "area"],
  },
  {
    id: 4,
    title: "Plots/Lands",
    icon: "https://s3.ap-south-1.amazonaws.com/lands-and-homes/icon_image/1683612259plots-lands.svg",
    tags: ["abc", "cdf"],
    status: ["budget", "bedroom", "construction status", "posted by", "area"],
  },
  {
    id: 5,
    title: "Projects",
    icon: "https://s3.ap-south-1.amazonaws.com/lands-and-homes/icon_image/1683612276projects.svg",
    tags: ["abc", "cdf"],
    status: ["budget", "bedroom", "construction status", "posted by", "area"],
  },
];
